package intchecker

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/unxed/f4/vfs"
)

type recordingReporter struct {
	calls     int
	lastTotal int
	lastSpeed string
	files     map[string]bool
}

func (r *recordingReporter) UpdateTransfer(action, filename string, currentPct int, totalText string, totalPct int, speedText string) {
	r.calls++
	r.lastTotal = totalPct
	r.lastSpeed = speedText
	if r.files == nil {
		r.files = map[string]bool{}
	}
	r.files[filename] = true
	if currentPct < 0 || currentPct > 100 || totalPct < 0 || totalPct > 100 {
		panic("progress out of range")
	}
}

func writeTestFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func readTestFile(t *testing.T, dir, name string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func TestRunGenerateWritesSortedSingleFile(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "b.txt", "abc")
	writeTestFile(t, dir, "a.txt", "abc")
	if err := os.Mkdir(filepath.Join(dir, "sub"), 0o700); err != nil {
		t.Fatal(err)
	}
	reporter := &recordingReporter{}
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"b.txt", "sub", "a.txt", ".."}, algorithm: AlgSHA256, output: "out.sha256"}
	res, err := runGenerate(context.Background(), job, reporter)
	if err != nil {
		t.Fatal(err)
	}
	if res.Written != 2 || len(res.Skipped) != 1 || res.Skipped[0] != "sub" || len(res.Failures) != 0 {
		t.Fatalf("result = %+v", res)
	}
	want := abcDigests[AlgSHA256] + " *a.txt\n" + abcDigests[AlgSHA256] + " *b.txt\n"
	if got := readTestFile(t, dir, "out.sha256"); got != want {
		t.Fatalf("checksum file =\n%q\nwant\n%q", got, want)
	}
	if reporter.lastTotal != 100 || !reporter.files["a.txt"] || !reporter.files["b.txt"] {
		t.Fatalf("progress = %+v", reporter)
	}
	// Progress carries elapsed time, ETA and hashing speed (issue #1623,
	// author's 3rd request): every UpdateTransfer call gets a non-empty
	// speed/time text, not just the final one.
	if reporter.lastSpeed == "" {
		t.Fatalf("progress speed/time text is empty")
	}
}

func TestRunGenerateSkipsItsOwnOutputFile(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "list.md5", "old")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"a.txt", "list.md5"}, algorithm: AlgMD5, output: "list.md5", overwrite: true}
	res, err := runGenerate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if res.Written != 1 {
		t.Fatalf("result = %+v", res)
	}
	if got, want := readTestFile(t, dir, "list.md5"), abcDigests[AlgMD5]+" *a.txt\n"; got != want {
		t.Fatalf("checksum file = %q, want %q", got, want)
	}
}

func TestRunGenerateDoesNotReplaceUnconfirmedExistingFile(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "out.md5", "keep me")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"a.txt"}, algorithm: AlgMD5, output: "out.md5"}
	if _, err := runGenerate(context.Background(), job, &recordingReporter{}); err == nil {
		t.Fatal("existing file replaced without the user's consent")
	}
	if got := readTestFile(t, dir, "out.md5"); got != "keep me" {
		t.Fatalf("existing file changed to %q", got)
	}
}

func TestRunGenerateCancelledWritesNothing(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"a.txt"}, algorithm: AlgMD5, output: "out.md5"}
	if _, err := runGenerate(ctx, job, &recordingReporter{}); !errors.Is(err, context.Canceled) {
		t.Fatalf("err = %v, want context.Canceled", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "out.md5")); !os.IsNotExist(err) {
		t.Fatalf("cancelled run left a checksum file: %v", err)
	}
}

func TestRunGenerateReportsMissingFilesAndKeepsTheRest(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"gone.txt", "a.txt"}, algorithm: AlgCRC32, output: "out.sfv"}
	res, err := runGenerate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if res.Written != 1 || len(res.Failures) != 1 || res.Failures[0].Name != "gone.txt" {
		t.Fatalf("result = %+v", res)
	}
	if got, want := readTestFile(t, dir, "out.sfv"), "; Generated by f4\na.txt 352441C2\n"; got != want {
		t.Fatalf("sfv = %q, want %q", got, want)
	}
}

func TestRunGenerateOnlyDirectoriesIsNothingToHash(t *testing.T) {
	dir := t.TempDir()
	if err := os.Mkdir(filepath.Join(dir, "sub"), 0o700); err != nil {
		t.Fatal(err)
	}
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"sub"}, algorithm: AlgMD5, output: "out.md5"}
	if _, err := runGenerate(context.Background(), job, &recordingReporter{}); !errors.Is(err, errNothingToHash) {
		t.Fatalf("err = %v, want errNothingToHash", err)
	}
}

func TestRunGenerateEmptyFileHashesToEmptyDigest(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "empty", "")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"empty"}, algorithm: AlgMD5, output: "out.md5"}
	if _, err := runGenerate(context.Background(), job, &recordingReporter{}); err != nil {
		t.Fatal(err)
	}
	if got, want := readTestFile(t, dir, "out.md5"), "d41d8cd98f00b204e9800998ecf8427e *empty\n"; got != want {
		t.Fatalf("checksum file = %q, want %q", got, want)
	}
}

func TestPercent(t *testing.T) {
	for _, tc := range []struct {
		done, total int64
		want        int
	}{{0, 0, 100}, {0, 10, 0}, {5, 10, 50}, {10, 10, 100}, {11, 10, 100}} {
		if got := percent(tc.done, tc.total); got != tc.want {
			t.Errorf("percent(%d, %d) = %d, want %d", tc.done, tc.total, got, tc.want)
		}
	}
}

func TestOutputForEveryMode(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "photos")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, algorithm: AlgSHA1, output: "list.sha1"}
	for _, tc := range []struct {
		mode          outputMode
		name          string
		target, name2 string
	}{
		{outputSingle, "a.jpg", "list.sha1", "a.jpg"},
		{outputSingle, "sub/b.jpg", "list.sha1", "sub/b.jpg"},
		{outputSeparate, "a.jpg", "a.jpg.sha1", "a.jpg"},
		{outputSeparate, "sub/b.jpg", "sub/b.jpg.sha1", "b.jpg"},
		{outputDirectory, "a.jpg", "photos.sha1", "a.jpg"},
		{outputDirectory, "sub/b.jpg", "sub/sub.sha1", "b.jpg"},
		{outputDisplay, "a.jpg", "", "a.jpg"},
	} {
		job.mode = tc.mode
		target, stored := job.outputFor(tc.name)
		if target != tc.target || stored != tc.name2 {
			t.Errorf("mode %d, %q: got %q/%q, want %q/%q", tc.mode, tc.name, target, stored, tc.target, tc.name2)
		}
	}
}

func TestRunGenerateSeparateFiles(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "b.txt", "abc")
	writeTestFile(t, dir, "a.txt.md5", "old")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"b.txt", "a.txt.md5", "a.txt"}, algorithm: AlgMD5, mode: outputSeparate, overwrite: true}
	res, err := runGenerate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if res.Written != 2 || len(res.Outputs) != 2 || res.Outputs[0] != "a.txt.md5" || res.Outputs[1] != "b.txt.md5" || len(res.WriteFailures) != 0 {
		t.Fatalf("result = %+v", res)
	}
	for _, name := range []string{"a.txt", "b.txt"} {
		if got, want := readTestFile(t, dir, name+".md5"), abcDigests[AlgMD5]+" *"+name+"\n"; got != want {
			t.Errorf("%s.md5 = %q, want %q", name, got, want)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "a.txt.md5.md5")); !os.IsNotExist(err) {
		t.Fatalf("the old checksum file was hashed as an input: %v", err)
	}
}

func TestRunGenerateSeparateSkipsExistingFiles(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "b.txt", "abc")
	writeTestFile(t, dir, "a.txt.sfv", "keep me")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"a.txt", "b.txt"}, algorithm: AlgCRC32, mode: outputSeparate, skipExisting: true}
	res, err := runGenerate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.SkippedExisting) != 1 || res.SkippedExisting[0] != "a.txt.sfv" || len(res.Outputs) != 1 || res.Written != 1 {
		t.Fatalf("result = %+v", res)
	}
	if got := readTestFile(t, dir, "a.txt.sfv"); got != "keep me" {
		t.Fatalf("skipped file changed to %q", got)
	}
	if got, want := readTestFile(t, dir, "b.txt.sfv"), "; Generated by f4\nb.txt 352441C2\n"; got != want {
		t.Fatalf("b.txt.sfv = %q, want %q", got, want)
	}
}

func TestRunGenerateSeparateKeepsUnconfirmedFileAndWritesTheRest(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "b.txt", "abc")
	writeTestFile(t, dir, "a.txt.md5", "keep me")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"a.txt", "b.txt"}, algorithm: AlgMD5, mode: outputSeparate}
	res, err := runGenerate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.WriteFailures) != 1 || res.WriteFailures[0].Name != "a.txt.md5" || len(res.Outputs) != 1 || res.Outputs[0] != "b.txt.md5" {
		t.Fatalf("result = %+v", res)
	}
	if got := readTestFile(t, dir, "a.txt.md5"); got != "keep me" {
		t.Fatalf("existing file changed to %q", got)
	}
}

func TestRunGenerateDirectoryFile(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "photos")
	if err := os.Mkdir(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "b.txt", "abc")
	writeTestFile(t, dir, "photos.sha256", "old")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"photos.sha256", "b.txt", "a.txt"}, algorithm: AlgSHA256, mode: outputDirectory, overwrite: true}
	res, err := runGenerate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if res.Written != 2 || len(res.Outputs) != 1 || res.Outputs[0] != "photos.sha256" {
		t.Fatalf("result = %+v", res)
	}
	want := abcDigests[AlgSHA256] + " *a.txt\n" + abcDigests[AlgSHA256] + " *b.txt\n"
	if got := readTestFile(t, dir, "photos.sha256"); got != want {
		t.Fatalf("photos.sha256 =\n%q\nwant\n%q", got, want)
	}
}

func TestRunGenerateDisplayWritesNothing(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "b.md5", "abc")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"b.md5", "a.txt"}, algorithm: AlgMD5, mode: outputDisplay}
	res, err := runGenerate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	want := abcDigests[AlgMD5] + " *a.txt\n" + abcDigests[AlgMD5] + " *b.md5\n"
	if res.Text != want || res.Written != 2 || len(res.Outputs) != 0 {
		t.Fatalf("result = %+v, want text %q", res, want)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 2 {
		t.Fatalf("display run created files: %v", entries)
	}
}

func TestExistingOutputs(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "b.txt", "abc")
	writeTestFile(t, dir, "b.txt.md5", "old")
	writeTestFile(t, dir, "list.md5", "old")
	fs := vfs.NewOSVFS(dir)
	job := generateJob{fs: fs, dir: dir, names: []string{"a.txt", "b.txt", "b.txt.md5", "gone"}, algorithm: AlgMD5, output: "list.md5"}
	for _, tc := range []struct {
		mode outputMode
		want []string
	}{
		{outputSingle, []string{"list.md5"}},
		{outputSeparate, []string{"b.txt.md5"}},
		{outputDirectory, nil},
		{outputDisplay, nil},
	} {
		job.mode = tc.mode
		var ignored generateResult
		inputs, err := collectInputs(context.Background(), job, &ignored, nil)
		if err != nil {
			t.Fatal(err)
		}
		got, err := existingOutputs(context.Background(), job, inputs)
		if err != nil {
			t.Fatal(err)
		}
		if len(got) != len(tc.want) || (len(got) > 0 && got[0] != tc.want[0]) {
			t.Errorf("mode %d: existing = %q, want %q", tc.mode, got, tc.want)
		}
	}
}
