// Package intchecker is f4's integrity checker: it generates checksum files
// (.sfv, .md5, .sha1, .sha256, .sha384, .sha512) for panel files and
// validates files against them. It follows the IntChecker plugin for Far
// Manager (https://github.com/lazyhamster/IntChecker), as requested in
// f4#1623.
//
// It offers "Generate hashes" with an algorithm choice for the marked files
// (or the file under the cursor), recursion into the marked directories,
// relative or absolute paths, a file mask filter and all four outputs -- a
// single file, a separate "<file><ext>" per file, one "<directory name><ext>"
// per directory ("sub/sub.md5" for the files of sub), and a window with the
// list that copies it to the clipboard or saves it -- and "Validate files" for
// the checksum file under the cursor or one the user names, asking for the
// directory when the listed files are not found. The checksum file encoding is
// chosen when generating (UTF-8, UTF-8 with BOM, the system ANSI or OEM
// codepage) and when validating (detected by default, like the viewer does).
//
// Invariants:
//   - Checksum files are written only after every selected file has been
//     read. A cancelled or failed run leaves no half-written checksum file
//     behind, and existing ones are replaced only after the user agreed (or
//     kept, when the user chose to skip them).
//   - Files that could not be read are left out of the checksum file and
//     reported to the user; one unreadable file does not throw away the
//     hashes of the others.
//   - Hash files use the formats other tools read: "<hex> *<name>" (GNU
//     coreutils binary mode, what md5sum -c / sha256sum -c and IntChecker
//     accept) and "<name> <CRC32>" for SFV, with LF line ends. They are
//     UTF-8 unless the user picks another encoding; a name that encoding
//     cannot store is left out and reported, never written mangled.
//   - Validation only reads. The algorithm comes from the checksum file's
//     extension and, when that is missing or does not fit, from the digest
//     length. Every listed file ends up OK, mismatched, not found or
//     unreadable; when none is found at all, the user is asked for the
//     directory instead of getting a report that lists them all as missing.
//   - Hashing goes through the standard library (hash/crc32, crypto/*), which
//     already uses the CPU's hardware acceleration where there is one.
package intchecker

import (
	"crypto/md5"  // #nosec G501 -- checksum file format, not a security use
	"crypto/sha1" // #nosec G505 -- checksum file format, not a security use
	"crypto/sha256"
	"crypto/sha512"
	"encoding/hex"
	"fmt"
	"hash"
	"hash/crc32"
	"strings"
)

// Algorithm is a checksum algorithm offered in the "Generate hashes" dialog.
// The values double as radio button indexes, in the order of algorithms.
type Algorithm int

const (
	AlgCRC32 Algorithm = iota
	AlgMD5
	AlgSHA1
	AlgSHA256
	AlgSHA384
	AlgSHA512
)

// DefaultAlgorithm is preselected in the dialog.
const DefaultAlgorithm = AlgMD5

type algorithmInfo struct {
	name string // shown in the dialog; algorithm names are not translated
	ext  string // extension of the checksum file, with the dot
	new  func() hash.Hash
}

var algorithms = []algorithmInfo{
	AlgCRC32:  {"CRC32 (SFV)", ".sfv", func() hash.Hash { return crc32.NewIEEE() }},
	AlgMD5:    {"MD5", ".md5", md5.New},
	AlgSHA1:   {"SHA-1", ".sha1", sha1.New},
	AlgSHA256: {"SHA-256", ".sha256", sha256.New},
	AlgSHA384: {"SHA-384", ".sha384", sha512.New384},
	AlgSHA512: {"SHA-512", ".sha512", sha512.New},
}

func (a Algorithm) valid() bool { return a >= 0 && int(a) < len(algorithms) }

// Name is the algorithm's display name.
func (a Algorithm) Name() string { return algorithms[a].name }

// Extension is the conventional extension of a checksum file of this kind.
func (a Algorithm) Extension() string { return algorithms[a].ext }

// New returns a fresh hash for the algorithm.
func (a Algorithm) New() hash.Hash { return algorithms[a].new() }

// algorithmNames lists the display names in radio button order.
func algorithmNames() []string {
	names := make([]string, len(algorithms))
	for i, info := range algorithms {
		names[i] = info.name
	}
	return names
}

// Entry is one hashed file: its name as written into the checksum file and
// its digest.
type Entry struct {
	Name string
	Sum  []byte
}

// FormatHashFile renders entries in the checksum file format of a.
func FormatHashFile(a Algorithm, entries []Entry) ([]byte, error) {
	if !a.valid() {
		return nil, fmt.Errorf("unknown checksum algorithm %d", int(a))
	}
	var b strings.Builder
	if a == AlgCRC32 {
		// SFV has no escaping, so a name with a line break cannot be stored.
		b.WriteString("; Generated by f4\n")
		for _, e := range entries {
			if strings.ContainsAny(e.Name, "\r\n") {
				return nil, fmt.Errorf("file name %q contains a line break and cannot be stored in an SFV file", e.Name)
			}
			fmt.Fprintf(&b, "%s %s\n", e.Name, strings.ToUpper(hex.EncodeToString(e.Sum)))
		}
		return []byte(b.String()), nil
	}
	for _, e := range entries {
		name, escaped := escapeCoreutilsName(e.Name)
		if escaped {
			// GNU coreutils: a leading backslash marks an escaped name.
			b.WriteByte('\\')
		}
		fmt.Fprintf(&b, "%s *%s\n", hex.EncodeToString(e.Sum), name)
	}
	return []byte(b.String()), nil
}

// escapeCoreutilsName escapes a file name the way md5sum/sha*sum do, so the
// line stays one line and the checkers read the name back unchanged.
func escapeCoreutilsName(name string) (string, bool) {
	if !strings.ContainsAny(name, "\\\n\r") {
		return name, false
	}
	r := strings.NewReplacer("\\", "\\\\", "\n", "\\n", "\r", "\\r")
	return r.Replace(name), true
}

// defaultOutputName is the checksum file name offered for a directory:
// "<directory name><extension>", like IntChecker does, or "checksums<ext>"
// when the directory has no usable name (a root).
func defaultOutputName(dirBase string, a Algorithm) string {
	base := strings.TrimSpace(dirBase)
	if base == "" || base == "." || base == ".." || strings.ContainsAny(base, `/\:`) {
		base = "checksums"
	}
	return base + a.Extension()
}

// switchExtension replaces the extension of a checksum file name typed in the
// dialog when the algorithm changes, but only when the name still carries the
// old algorithm's extension -- a name the user chose on purpose stays as is.
func switchExtension(name string, from, to Algorithm) string {
	if from.valid() && strings.HasSuffix(strings.ToLower(name), from.Extension()) {
		return name[:len(name)-len(from.Extension())] + to.Extension()
	}
	return name
}
