package intchecker

import (
	"encoding/hex"
	"strings"
	"testing"
)

// Known digests of "abc" (FIPS 180 / RFC 1321 test vectors, CRC-32/IEEE).
var abcDigests = map[Algorithm]string{
	AlgCRC32:  "352441c2",
	AlgMD5:    "900150983cd24fb0d6963f7d28e17f72",
	AlgSHA1:   "a9993e364706816aba3e25717850c26c9cd0d89d",
	AlgSHA256: "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
	AlgSHA384: "cb00753f45a35e8bb5a03d699ac65007272c32ab0eded1631a8b605a43ff5bed8086072ba1e7cc2358baeca134c825a7",
	AlgSHA512: "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f",
}

func TestEveryAlgorithmMatchesItsTestVector(t *testing.T) {
	if len(abcDigests) != len(algorithms) {
		t.Fatalf("test vectors cover %d of %d algorithms", len(abcDigests), len(algorithms))
	}
	for a, want := range abcDigests {
		h := a.New()
		_, _ = h.Write([]byte("abc"))
		if got := hex.EncodeToString(h.Sum(nil)); got != want {
			t.Errorf("%s(abc) = %s, want %s", a.Name(), got, want)
		}
	}
}

func TestExtensionsAreDistinctAndDotted(t *testing.T) {
	seen := map[string]bool{}
	for i := range algorithms {
		ext := Algorithm(i).Extension()
		if !strings.HasPrefix(ext, ".") || seen[ext] {
			t.Errorf("algorithm %d has bad or duplicate extension %q", i, ext)
		}
		seen[ext] = true
	}
	if names := algorithmNames(); len(names) != len(algorithms) || names[AlgSHA256] != "SHA-256" {
		t.Fatalf("algorithmNames() = %q", names)
	}
}

func TestFormatHashFileCoreutilsFormat(t *testing.T) {
	sum, _ := hex.DecodeString(abcDigests[AlgMD5])
	got, err := FormatHashFile(AlgMD5, []Entry{{Name: "a b.txt", Sum: sum}, {Name: "файл.bin", Sum: sum}})
	if err != nil {
		t.Fatal(err)
	}
	want := abcDigests[AlgMD5] + " *a b.txt\n" + abcDigests[AlgMD5] + " *файл.bin\n"
	if string(got) != want {
		t.Fatalf("md5 file =\n%q\nwant\n%q", got, want)
	}
}

func TestFormatHashFileEscapesNamesLikeCoreutils(t *testing.T) {
	sum := []byte{0xab}
	got, err := FormatHashFile(AlgSHA1, []Entry{{Name: "a\\b\nc", Sum: sum}})
	if err != nil {
		t.Fatal(err)
	}
	if want := "\\ab *a\\\\b\\nc\n"; string(got) != want {
		t.Fatalf("escaped line = %q, want %q", got, want)
	}
}

func TestFormatHashFileSFV(t *testing.T) {
	sum, _ := hex.DecodeString(abcDigests[AlgCRC32])
	got, err := FormatHashFile(AlgCRC32, []Entry{{Name: "abc.txt", Sum: sum}})
	if err != nil {
		t.Fatal(err)
	}
	if want := "; Generated by f4\nabc.txt 352441C2\n"; string(got) != want {
		t.Fatalf("sfv = %q, want %q", got, want)
	}
	if _, err := FormatHashFile(AlgCRC32, []Entry{{Name: "bad\nname", Sum: sum}}); err == nil {
		t.Fatal("SFV accepted a name with a line break")
	}
}

func TestFormatHashFileRejectsUnknownAlgorithm(t *testing.T) {
	if _, err := FormatHashFile(Algorithm(len(algorithms)), nil); err == nil {
		t.Fatal("unknown algorithm accepted")
	}
	if _, err := FormatHashFile(Algorithm(-1), nil); err == nil {
		t.Fatal("negative algorithm accepted")
	}
}

func TestDefaultOutputName(t *testing.T) {
	for _, tc := range []struct {
		dir  string
		a    Algorithm
		want string
	}{
		{"photos", AlgMD5, "photos.md5"},
		{"disk1", AlgCRC32, "disk1.sfv"},
		{"/", AlgSHA256, "checksums.sha256"},
		{`C:\`, AlgSHA1, "checksums.sha1"},
		{"", AlgSHA512, "checksums.sha512"},
	} {
		if got := defaultOutputName(tc.dir, tc.a); got != tc.want {
			t.Errorf("defaultOutputName(%q, %s) = %q, want %q", tc.dir, tc.a.Name(), got, tc.want)
		}
	}
}

func TestSwitchExtensionKeepsUserChosenNames(t *testing.T) {
	if got := switchExtension("photos.md5", AlgMD5, AlgSHA256); got != "photos.sha256" {
		t.Errorf("default name not switched: %q", got)
	}
	if got := switchExtension("photos.MD5", AlgMD5, AlgCRC32); got != "photos.sfv" {
		t.Errorf("upper-case extension not switched: %q", got)
	}
	if got := switchExtension("my-list.txt", AlgMD5, AlgSHA1); got != "my-list.txt" {
		t.Errorf("user name changed: %q", got)
	}
}

func TestValidOutputName(t *testing.T) {
	for name, want := range map[string]bool{
		"photos.md5": true,
		"":           false,
		".":          false,
		"..":         false,
		"a/b.md5":    false,
		`a\b.md5`:    false,
	} {
		if got := validOutputName(name); got != want {
			t.Errorf("validOutputName(%q) = %v, want %v", name, got, want)
		}
	}
}
