package intchecker

import (
	"bytes"
	"context"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/unxed/f4/internal/i18n"
	"github.com/unxed/f4/vfs"
	"github.com/unxed/vtui"
)

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func TestParseHashFileReadsWhatFormatHashFileWrites(t *testing.T) {
	names := []string{"a.txt", "with space.bin", `back\slash`, "line\nbreak", "sub/dir.txt"}
	for a := range algorithms {
		alg := Algorithm(a)
		var entries []Entry
		for _, name := range names {
			if alg == AlgCRC32 && strings.Contains(name, "\n") {
				continue // SFV cannot store it
			}
			entries = append(entries, Entry{Name: name, Sum: mustHex(t, abcDigests[alg])})
		}
		data, err := FormatHashFile(alg, entries)
		if err != nil {
			t.Fatal(err)
		}
		got, err := ParseHashFile("list"+alg.Extension(), data)
		if err != nil {
			t.Fatalf("%s: %v", alg.Name(), err)
		}
		if got.Algorithm != alg || got.Malformed != 0 || len(got.Entries) != len(entries) {
			t.Fatalf("%s: parsed %+v", alg.Name(), got)
		}
		for i, e := range entries {
			if got.Entries[i].Name != e.Name || !bytes.Equal(got.Entries[i].Sum, e.Sum) {
				t.Errorf("%s: entry %d = %q %x, want %q %x", alg.Name(), i, got.Entries[i].Name, got.Entries[i].Sum, e.Name, e.Sum)
			}
		}
	}
}

func TestParseHashFileAcceptsOtherToolsLines(t *testing.T) {
	md5 := abcDigests[AlgMD5]
	data := "\xef\xbb\xbf# comment\r\n" +
		md5 + "  text mode.txt\r\n" +
		md5 + " single.txt\n" +
		strings.ToUpper(md5) + " *upper.txt\n" +
		"\n   \n" +
		"garbage line\n" +
		md5 + " *\n"
	got, err := ParseHashFile("LIST.MD5", []byte(data))
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"text mode.txt", "single.txt", "upper.txt"}
	if got.Algorithm != AlgMD5 || len(got.Entries) != len(want) || got.Malformed != 2 {
		t.Fatalf("parsed %+v", got)
	}
	for i, name := range want {
		if got.Entries[i].Name != name {
			t.Errorf("entry %d = %q, want %q", i, got.Entries[i].Name, name)
		}
	}
}

func TestParseHashFileReadsSFV(t *testing.T) {
	data := "; Generated by some tool\n" +
		"name with spaces.txt 352441C2\n" +
		"tabbed.txt\t352441c2  \n" +
		"nocrc.txt\n"
	got, err := ParseHashFile("disk.sfv", []byte(data))
	if err != nil {
		t.Fatal(err)
	}
	if got.Algorithm != AlgCRC32 || len(got.Entries) != 2 || got.Malformed != 1 ||
		got.Entries[0].Name != "name with spaces.txt" || got.Entries[1].Name != "tabbed.txt" {
		t.Fatalf("parsed %+v", got)
	}
}

func TestParseHashFilePicksAlgorithmByLength(t *testing.T) {
	for _, tc := range []struct {
		name string
		sum  string
		want Algorithm
	}{
		{"checksums.txt", abcDigests[AlgSHA1], AlgSHA1},
		{"mislabelled.md5", abcDigests[AlgSHA256], AlgSHA256},
		{"noext", abcDigests[AlgSHA384], AlgSHA384},
		{"CHECKSUMS", abcDigests[AlgSHA512], AlgSHA512},
		{"crc.txt", abcDigests[AlgCRC32], AlgCRC32},
	} {
		got, err := ParseHashFile(tc.name, []byte(tc.sum+" *a.txt\n"))
		if err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		if got.Algorithm != tc.want || len(got.Entries) != 1 {
			t.Errorf("%s: algorithm %s, entries %d; want %s", tc.name, got.Algorithm.Name(), len(got.Entries), tc.want.Name())
		}
	}
}

func TestParseHashFileCountsOtherLengthsAsMalformed(t *testing.T) {
	data := abcDigests[AlgMD5] + " *a\n" + abcDigests[AlgSHA1] + " *b\n" + abcDigests[AlgMD5] + " *c\n"
	got, err := ParseHashFile("x.md5", []byte(data))
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Entries) != 2 || got.Malformed != 1 {
		t.Fatalf("parsed %+v", got)
	}
}

func TestParseHashFileErrors(t *testing.T) {
	if _, err := ParseHashFile("x.md5", []byte("; nothing\n\n")); !errors.Is(err, errNoChecksums) {
		t.Fatalf("empty file: err = %v", err)
	}
	if _, err := ParseHashFile("x.txt", []byte("0011223344 *a\n")); !errors.Is(err, errUnknownHashLength) {
		t.Fatalf("5-byte digest: err = %v", err)
	}
	if _, err := ParseHashFile("x.md5", []byte(`\`+abcDigests[AlgMD5]+` *bad\qescape`+"\n")); !errors.Is(err, errNoChecksums) {
		t.Fatalf("bad escape: err = %v", err)
	}
}

func TestChecksumFileNames(t *testing.T) {
	for name, want := range map[string]bool{
		"a.md5": true, "A.SHA256": true, "x.sfv": true, "y.sha384": true, "z.sha512": true, "w.sha1": true,
		".md5": false, "a.txt": false, "md5": false, "a.sha": false,
	} {
		if got := isChecksumFileName(name); got != want {
			t.Errorf("isChecksumFileName(%q) = %v, want %v", name, got, want)
		}
	}
}

// validateFixture is a directory with a.txt ("abc", matches), b.txt (changed
// since), sub/d.txt (matches) and a directory "dir", plus the checksum list
// for a.txt, b.txt, c.txt (missing), dir and sub/d.txt.
func validateFixture(t *testing.T) (string, ChecksumFile) {
	t.Helper()
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "b.txt", "abd")
	if err := os.Mkdir(filepath.Join(dir, "sub"), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(filepath.Join(dir, "dir"), 0o700); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, dir, filepath.Join("sub", "d.txt"), "abc")
	sum := mustHex(t, abcDigests[AlgSHA256])
	file := ChecksumFile{Algorithm: AlgSHA256, Entries: []Entry{
		{Name: "a.txt", Sum: sum},
		{Name: "b.txt", Sum: sum},
		{Name: "c.txt", Sum: sum},
		{Name: "dir", Sum: sum},
		{Name: "sub/d.txt", Sum: sum},
	}}
	return dir, file
}

func TestRunValidateSortsEveryFileIntoAVerdict(t *testing.T) {
	dir, file := validateFixture(t)
	reporter := &recordingReporter{}
	job := validateJob{fs: vfs.NewOSVFS(dir), dir: dir, file: file}
	res, err := runValidate(context.Background(), job, reporter)
	if err != nil {
		t.Fatal(err)
	}
	want := []entryStatus{statusOK, statusMismatch, statusMissing, statusReadError, statusOK}
	if len(res.Results) != len(want) {
		t.Fatalf("results = %+v", res.Results)
	}
	for i, status := range want {
		if res.Results[i].Name != file.Entries[i].Name || res.Results[i].Status != status {
			t.Errorf("result %d = %+v, want %s %d", i, res.Results[i], file.Entries[i].Name, status)
		}
	}
	if res.Counts != [statusCount]int{2, 1, 1, 1} {
		t.Fatalf("counts = %v", res.Counts)
	}
	if reporter.lastTotal != 100 || !reporter.files["sub/d.txt"] {
		t.Fatalf("progress = %+v", reporter)
	}
	if reporter.lastSpeed == "" {
		t.Fatalf("progress speed/time text is empty")
	}
}

// TestRunValidateIgnoreMissing covers f4#1623 point 2's "Ignore missing
// files" checkbox: a listed file that is not on disk (c.txt in the fixture)
// disappears from the report entirely instead of counting as a problem,
// while every other verdict -- OK, mismatch, read error -- is unaffected.
func TestRunValidateIgnoreMissing(t *testing.T) {
	dir, file := validateFixture(t)
	job := validateJob{fs: vfs.NewOSVFS(dir), dir: dir, file: file, ignoreMissing: true}
	res, err := runValidate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	want := []entryStatus{statusOK, statusMismatch, statusReadError, statusOK}
	if len(res.Results) != len(want) {
		t.Fatalf("results = %+v", res.Results)
	}
	for i, status := range want {
		if res.Results[i].Status != status {
			t.Errorf("result %d = %+v, want status %d", i, res.Results[i], status)
		}
		if res.Results[i].Name == "c.txt" {
			t.Errorf("the missing file was not ignored: %+v", res.Results[i])
		}
	}
	if res.Counts != [statusCount]int{2, 1, 0, 1} {
		t.Fatalf("counts = %v, want missing = 0", res.Counts)
	}
}

// TestRunValidateIgnoreMissingAllMissingStillAsksForDirectory checks that
// "Ignore missing files" does not change errAllMissing: checking zero files
// is still meaningless, and the caller must still be asked for another
// directory (f4#1623 point 2 only asked to stop *counting* missing files as
// a problem, not to silently accept an empty check).
func TestRunValidateIgnoreMissingAllMissingStillAsksForDirectory(t *testing.T) {
	_, file := validateFixture(t)
	empty := t.TempDir()
	job := validateJob{fs: vfs.NewOSVFS(empty), dir: empty, file: file, ignoreMissing: true}
	if _, err := runValidate(context.Background(), job, &recordingReporter{}); !errors.Is(err, errAllMissing) {
		t.Fatalf("err = %v, want errAllMissing", err)
	}
}

// TestRunValidateStopOnMismatch covers f4#1623 point 2's "Stop on first
// mismatch" checkbox: the run ends right after the first mismatched file
// (b.txt in the fixture, the second entry) instead of checking the rest of
// the list, and validateResult.StoppedEarly records that it did.
func TestRunValidateStopOnMismatch(t *testing.T) {
	dir, file := validateFixture(t)
	job := validateJob{fs: vfs.NewOSVFS(dir), dir: dir, file: file, stopOnMismatch: true}
	res, err := runValidate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if !res.StoppedEarly {
		t.Fatal("StoppedEarly not set")
	}
	want := []entryStatus{statusOK, statusMismatch}
	if len(res.Results) != len(want) {
		t.Fatalf("results = %+v, want a two-entry prefix", res.Results)
	}
	for i, status := range want {
		if res.Results[i].Status != status {
			t.Errorf("result %d = %+v, want status %d", i, res.Results[i], status)
		}
	}
	if res.Counts != [statusCount]int{1, 1, 0, 0} {
		t.Fatalf("counts = %v, want only the checked prefix", res.Counts)
	}
	if !strings.Contains(validateReport(res, 0), vtui.Msg("IntChecker.StoppedOnMismatch")) {
		t.Fatalf("report does not mention the early stop:\n%s", validateReport(res, 0))
	}
}

// TestRunValidateStopOnMismatchWithoutAnyMismatchRunsToCompletion makes sure
// "Stop on first mismatch" only ever cuts a run short, never lengthens or
// otherwise changes one that never mismatches.
func TestRunValidateStopOnMismatchWithoutAnyMismatchRunsToCompletion(t *testing.T) {
	dir := t.TempDir()
	makeTree(t, dir, "a.txt", "sub/b.txt")
	file := ChecksumFile{Algorithm: AlgSHA256, Entries: []Entry{
		{Name: "a.txt", Sum: mustHex(t, abcDigests[AlgSHA256])},
		{Name: "sub/b.txt", Sum: mustHex(t, abcDigests[AlgSHA256])},
	}}
	job := validateJob{fs: vfs.NewOSVFS(dir), dir: dir, file: file, stopOnMismatch: true}
	res, err := runValidate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if res.StoppedEarly || res.Counts[statusOK] != 2 || len(res.Results) != 2 {
		t.Fatalf("result = %+v", res)
	}
}

func TestRunValidateFindsBackslashNames(t *testing.T) {
	dir, _ := validateFixture(t)
	file := ChecksumFile{Algorithm: AlgMD5, Entries: []Entry{{Name: `sub\d.txt`, Sum: mustHex(t, abcDigests[AlgMD5])}}}
	res, err := runValidate(context.Background(), validateJob{fs: vfs.NewOSVFS(dir), dir: dir, file: file}, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if res.Counts[statusOK] != 1 {
		t.Fatalf("results = %+v", res.Results)
	}
}

func TestRunValidateAcceptsAbsoluteNames(t *testing.T) {
	dir, _ := validateFixture(t)
	file := ChecksumFile{Algorithm: AlgMD5, Entries: []Entry{{Name: filepath.Join(dir, "a.txt"), Sum: mustHex(t, abcDigests[AlgMD5])}}}
	other := t.TempDir()
	res, err := runValidate(context.Background(), validateJob{fs: vfs.NewOSVFS(other), dir: other, file: file}, &recordingReporter{})
	if err != nil || res.Counts[statusOK] != 1 {
		t.Fatalf("res = %+v, err = %v", res, err)
	}
}

func TestRunValidateAllMissingAsksForDirectory(t *testing.T) {
	_, file := validateFixture(t)
	empty := t.TempDir()
	_, err := runValidate(context.Background(), validateJob{fs: vfs.NewOSVFS(empty), dir: empty, file: file}, &recordingReporter{})
	if !errors.Is(err, errAllMissing) {
		t.Fatalf("err = %v, want errAllMissing", err)
	}
}

func TestRunValidateCancelled(t *testing.T) {
	dir, file := validateFixture(t)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := runValidate(ctx, validateJob{fs: vfs.NewOSVFS(dir), dir: dir, file: file}, &recordingReporter{}); !errors.Is(err, context.Canceled) {
		t.Fatalf("err = %v, want context.Canceled", err)
	}
}

func TestValidateReport(t *testing.T) {
	var ok validateResult
	ok.add("a", statusOK, nil)
	ok.add("b", statusOK, nil)
	if got, want := validateReport(ok, 0), fmt.Sprintf(vtui.Msg("IntChecker.AllOK"), 2); got != want {
		t.Fatalf("all OK report = %q, want %q", got, want)
	}

	var bad validateResult
	bad.add("fine", statusOK, nil)
	bad.add("changed", statusMismatch, nil)
	bad.add("broken", statusReadError, errors.New("boom"))
	for i := 0; i < 12; i++ {
		bad.add(fmt.Sprintf("gone%d", i), statusMissing, nil)
	}
	report := validateReport(bad, 3)
	for _, want := range []string{
		fmt.Sprintf(vtui.Msg("IntChecker.ValidateSummary"), 15, 1, 1, 12, 1),
		vtui.Msg("IntChecker.StatusMismatch") + ": changed",
		vtui.Msg("IntChecker.StatusReadError") + ": broken (boom)",
		vtui.Msg("IntChecker.StatusMissing") + ": gone7",
		fmt.Sprintf(vtui.Msg("IntChecker.MoreErrors"), 4),
		fmt.Sprintf(vtui.Msg("IntChecker.Malformed"), 3),
	} {
		if !strings.Contains(report, want) {
			t.Errorf("report lacks %q:\n%s", want, report)
		}
	}
	if strings.Contains(report, "gone8") || strings.Contains(report, ": fine") {
		t.Errorf("report lists too much:\n%s", report)
	}
}

func TestResolveValidateInput(t *testing.T) {
	panelDir := t.TempDir()
	fs := vfs.NewOSVFS(panelDir)
	if _, _, ok := resolveValidateInput(fs, panelDir, "  ", "x"); ok {
		t.Fatal("empty checksum file accepted")
	}
	hashPath, dir, ok := resolveValidateInput(fs, panelDir, " list.md5 ", "")
	if !ok || hashPath != filepath.Join(panelDir, "list.md5") || dir != panelDir {
		t.Fatalf("relative: %q %q %v", hashPath, dir, ok)
	}
	other := t.TempDir()
	abs := filepath.Join(other, "x.sfv")
	hashPath, dir, ok = resolveValidateInput(fs, panelDir, abs, "sub")
	if !ok || hashPath != abs || dir != filepath.Join(panelDir, "sub") {
		t.Fatalf("absolute: %q %q %v", hashPath, dir, ok)
	}
}

// taskAppMock runs progress tasks synchronously and collects messages.
type taskAppMock struct {
	appMock
	messages chan string
}

func (a *taskAppMock) RunAdvancedProgressTask(_ string, _ bool, worker func(context.Context, vfs.TaskReporter) error, onComplete func(error)) {
	onComplete(worker(context.Background(), nopTaskReporter{}))
}

func (a *taskAppMock) Message(_, msg string, _ []string) int {
	a.messages <- msg
	return 0
}

type nopTaskReporter struct{}

func (nopTaskReporter) UpdateScan(string, int64, int64)                         {}
func (nopTaskReporter) UpdateTransfer(string, string, int, string, int, string) {}
func (nopTaskReporter) IsCancelled() bool                                       { return false }

func TestStartValidateReportsResult(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "list.sfv", "a.txt 352441C2\n")
	app := &taskAppMock{messages: make(chan string, 1)}
	fs := vfs.NewOSVFS(dir)
	startValidate(app, fs, filepath.Join(dir, "list.sfv"), dir, validateOptions{encoding: autoDetectEncoding}, nil)
	if got, want := <-app.messages, fmt.Sprintf(vtui.Msg("IntChecker.AllOK"), 1); got != want {
		t.Fatalf("message = %q, want %q", got, want)
	}
}

func TestStartValidateReportsUnreadableChecksumFile(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "empty.md5", "")
	app := &taskAppMock{messages: make(chan string, 1)}
	fs := vfs.NewOSVFS(dir)
	startValidate(app, fs, filepath.Join(dir, "empty.md5"), dir, validateOptions{encoding: autoDetectEncoding}, nil)
	if got, want := <-app.messages, fmt.Sprintf(vtui.Msg("IntChecker.NoChecksums"), filepath.Join(dir, "empty.md5")); got != want {
		t.Fatalf("message = %q, want %q", got, want)
	}
	startValidate(app, fs, filepath.Join(dir, "empty.md5"), filepath.Join(dir, "nope"), validateOptions{encoding: autoDetectEncoding}, nil)
	if got := <-app.messages; got != fmt.Sprintf(vtui.Msg("IntChecker.DirNotFound"), filepath.Join(dir, "nope")) {
		t.Fatalf("message = %q", got)
	}
}

func initValidateTestScreen(t *testing.T) *vtui.ScreenBuf {
	t.Helper()
	vtui.SetDefaultPalette()
	scr := vtui.NewSilentScreenBuf()
	scr.AllocBuf(80, 25)
	vtui.FrameManager.Init(scr)
	return scr
}

func TestStartValidateAsksForDirectoryWhenNothingIsFound(t *testing.T) {
	initValidateTestScreen(t)
	dir := t.TempDir()
	writeTestFile(t, dir, "list.md5", abcDigests[AlgMD5]+" *elsewhere.txt\n")
	app := &taskAppMock{messages: make(chan string, 1)}
	store, err := newSettingsStore(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	p := &Plugin{store: store}
	startValidate(app, vfs.NewOSVFS(dir), filepath.Join(dir, "list.md5"), dir, validateOptions{encoding: autoDetectEncoding}, p.openValidateDialog)
	if _, ok := vtui.FrameManager.GetTopFrame().(*vtui.Window); !ok {
		t.Fatalf("top frame = %T, want the directory dialog", vtui.FrameManager.GetTopFrame())
	}
	select {
	case msg := <-app.messages:
		t.Fatalf("unexpected message %q", msg)
	default:
	}
}

// TestValidateDialogDump renders both states of the dialog in English and
// Russian; run with -v to see the text dumps.
func TestValidateDialogDump(t *testing.T) {
	t.Cleanup(func() { i18n.InitLang("", "", "") })
	for _, lang := range []string{"en", "ru"} {
		i18n.InitLang(lang, "en", "")
		for _, note := range []string{"", vtui.Msg("IntChecker.FilesNotFound")} {
			scr := initValidateTestScreen(t)
			d := newValidateDialog(note, "/home/user/photos.md5", "/mnt/cdrom", validateOptions{encoding: autoDetectEncoding})
			d.win.Show(scr)
			var dump bytes.Buffer
			scr.Dump(&dump)
			text, _, _ := strings.Cut(dump.String(), "--- CELL METADATA")
			for _, want := range []string{"/home/user/photos.md5", "/mnt/cdrom", strings.ReplaceAll(vtui.Msg("IntChecker.ValidateTitle"), "&", ""),
				strings.ReplaceAll(vtui.Msg("IntChecker.FileEncoding"), "&", "") + " " + vtui.Msg("IntChecker.EncodingAuto"),
				strings.ReplaceAll(vtui.Msg("IntChecker.IgnoreMissing"), "&", ""),
				strings.ReplaceAll(vtui.Msg("IntChecker.StopOnMismatch"), "&", "")} {
				if !strings.Contains(text, want) {
					t.Errorf("%s dump lacks %q:\n%s", lang, want, text)
				}
			}
			if note != "" && !strings.Contains(text, note) {
				t.Errorf("%s dump lacks the note:\n%s", lang, text)
			}
			t.Logf("%s, note=%v:\n%s", lang, note != "", text)
		}
	}
}

// TestNewValidateDialogAppliesOptions checks that every validateOptions
// field lands on the right widget when the dialog is built.
func TestNewValidateDialogAppliesOptions(t *testing.T) {
	initValidateTestScreen(t)
	opts := validateOptions{encoding: fileEncoding{Codepage: utf8Codepage}, ignoreMissing: true, stopOnMismatch: true}
	d := newValidateDialog("", "", "", opts)
	if got := d.encoding.selected(); got != opts.encoding {
		t.Errorf("encoding = %+v, want %+v", got, opts.encoding)
	}
	if d.ignoreMissing.State != 1 {
		t.Errorf("ignoreMissing = %d, want 1", d.ignoreMissing.State)
	}
	if d.stopOnMismatch.State != 1 {
		t.Errorf("stopOnMismatch = %d, want 1", d.stopOnMismatch.State)
	}

	off := newValidateDialog("", "", "", validateOptions{encoding: opts.encoding})
	if off.ignoreMissing.State != 0 || off.stopOnMismatch.State != 0 {
		t.Errorf("checkboxes not off by default: ignoreMissing=%d stopOnMismatch=%d", off.ignoreMissing.State, off.stopOnMismatch.State)
	}
}

// TestQuickAndDialogValidateOptions covers f4#1623 point 2's two entry
// points into "Validate files": the quick, cursor-on-checksum-file path
// (quickValidateOptions) keeps auto-detecting the encoding but still applies
// the persisted checkboxes, while the dialog's defaults
// (dialogValidateOptions) also default the encoding to whatever "Generate
// hashes" last used -- the literal ask ("by default, the same encoding as
// for generation").
func TestQuickAndDialogValidateOptions(t *testing.T) {
	store, err := newSettingsStore(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	settings := DefaultSettings()
	settings.Encoding = fileEncoding{Codepage: utf8Codepage, BOM: true}
	settings.ValidateIgnoreMissing = true
	settings.ValidateStopOnMismatch = true
	if err := store.save(settings); err != nil {
		t.Fatal(err)
	}
	p := &Plugin{store: store}

	quick := p.quickValidateOptions()
	if quick.encoding != autoDetectEncoding {
		t.Errorf("quick encoding = %+v, want auto-detect", quick.encoding)
	}
	if !quick.ignoreMissing || !quick.stopOnMismatch {
		t.Errorf("quick options dropped the persisted checkboxes: %+v", quick)
	}

	dialog := p.dialogValidateOptions()
	if dialog.encoding != settings.Encoding {
		t.Errorf("dialog encoding = %+v, want %+v (same as generation)", dialog.encoding, settings.Encoding)
	}
	if !dialog.ignoreMissing || !dialog.stopOnMismatch {
		t.Errorf("dialog options dropped the persisted checkboxes: %+v", dialog)
	}
}

// TestSubmitValidatePersistsCheckboxesNotEncoding drives submitValidate (the
// dialog's real Ok handler) end to end and checks what actually landed on
// disk: the two checkboxes follow the dialog, the encoding choice does not
// (f4#1623 point 2 -- see saveValidateOptions), and the generate settings
// already on disk survive untouched.
func TestSubmitValidatePersistsCheckboxesNotEncoding(t *testing.T) {
	initValidateTestScreen(t)
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "list.md5", abcDigests[AlgMD5]+" *a.txt\n")
	configDir := t.TempDir()
	store, err := newSettingsStore(configDir)
	if err != nil {
		t.Fatal(err)
	}
	seed := DefaultSettings()
	seed.Algorithm = AlgSHA512
	seed.Encoding = fileEncoding{Codepage: utf8Codepage, BOM: true}
	if err := store.save(seed); err != nil {
		t.Fatal(err)
	}
	p := &Plugin{api: &hostMock{}, store: store}
	fs := vfs.NewOSVFS(dir)
	app := &taskAppMock{appMock: appMock{fs: fs}, messages: make(chan string, 1)}

	d := newValidateDialog("", "list.md5", "", p.dialogValidateOptions())
	d.ignoreMissing.State = 1
	d.stopOnMismatch.State = 1
	// A different encoding than what is persisted, to prove it does not
	// overwrite Settings.Encoding.
	d.encoding = newEncodingCombo(24, readEncodingChoices(), fileEncoding{Codepage: utf8Codepage})
	p.submitValidate(app, fs, dir, d)
	if got, want := <-app.messages, fmt.Sprintf(vtui.Msg("IntChecker.AllOK"), 1); got != want {
		t.Fatalf("message = %q, want %q", got, want)
	}

	got := p.store.snapshot()
	if !got.ValidateIgnoreMissing || !got.ValidateStopOnMismatch {
		t.Fatalf("checkboxes not persisted: %+v", got)
	}
	if got.Algorithm != AlgSHA512 || got.Encoding != seed.Encoding {
		t.Fatalf("submitValidate touched the generate settings: %+v", got)
	}
}

// TestShowValidateQuickRunAppliesPersistedIgnoreMissing is an end-to-end
// check of f4#1623 point 2's most common path: the cursor already sits on a
// checksum file, so "Validate files" never shows a dialog, yet the
// persisted "Ignore missing files" checkbox must still apply -- otherwise
// the setting would be unreachable for exactly the workflow the original
// f4#1623 spec made the default.
func TestShowValidateQuickRunAppliesPersistedIgnoreMissing(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "list.md5", abcDigests[AlgMD5]+" *a.txt\n"+abcDigests[AlgMD5]+" *missing.txt\n")
	store, err := newSettingsStore(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	settings := DefaultSettings()
	settings.ValidateIgnoreMissing = true
	if err := store.save(settings); err != nil {
		t.Fatal(err)
	}
	p := &Plugin{store: store}
	app := &taskAppMock{appMock: appMock{fs: vfs.NewOSVFS(dir), cursor: "list.md5"}, messages: make(chan string, 1)}
	p.showValidate(app)
	if got, want := <-app.messages, fmt.Sprintf(vtui.Msg("IntChecker.AllOK"), 1); got != want {
		t.Fatalf("message = %q, want %q (missing.txt should have been ignored)", got, want)
	}
}
