# Production and shell tests must package exactly the same QML component graph.
# Paths are relative to qt/host; production keeps these resource aliases even
# though its CMake target is configured from a clean child directory.
set(F4_HOST_QML_FILES
  qml/main.qml
  qml/F4HostWindow.qml
  qml/PanelSplitter.qml
  qml/GalleryPanelHost.qml
  qml/GalleryPanelHostAdapter.qml
  qml/GalleryPanelInputRouter.qml
  qml/GalleryViewerHost.qml
  qml/HostPixelAlignedImage.qml
  qml/HostPresentationUtilities.qml
  qml/FilePanelView.qml
  qml/PanelPairSurface.qml
  qml/PanelsSurface.qml
  qml/ShellSurfaceHost.qml
  qml/ShellShortcuts.qml
  qml/ShellSceneStore.qml
  qml/ShellInteractionController.qml
  qml/FilePanelChrome.qml
  qml/PanelRendererMenu.qml
  qml/QuickViewPanelView.qml
  qml/InfoPanelView.qml
  qml/CommandLineView.qml
  qml/ActivityBoundedCursorBlink.qml
  qml/ConsoleRunRow.qml
  qml/DocumentSurface.qml
  qml/DocumentHeader.qml
  qml/DocumentRowDelegate.qml
  qml/DocumentViewportController.qml
  qml/DocumentWindowPresenter.qml
  qml/DocumentRowPool.qml
  qml/DocumentTerminalSelectionController.qml
  qml/DocumentEditorPointerController.qml
  qml/TerminalBackdrop.qml
  qml/OperationsQueueSurface.qml
  qml/OperationsQueueController.qml
  qml/F4Button.qml
  qml/F4TextField.qml
  qml/F4CheckBox.qml
  qml/F4RadioButton.qml
  qml/F4ComboBox.qml
  qml/F4ScrollBar.qml
  qml/F4Slider.qml
  qml/F4ToolTip.qml
  qml/DialogButton.qml
  qml/QueueActionButton.qml
  qml/QueueSummaryItem.qml
  qml/ConfigDialogButton.qml
  qml/ThemeRenderTypeComboBox.qml
  qml/ThemeBooleanOption.qml
  qml/ThemeEditor.qml
  qml/ThemeDraftModel.qml
  qml/HostThemePalette.qml
  qml/ThemeColorWheel.qml
  qml/ThemeColorEditorPane.qml
  qml/ThemeEditorFooter.qml
  qml/SemanticMenuBar.qml
  qml/ShellTitleBar.qml
  qml/WorkspaceTabs.qml
  qml/DialogCheckBox.qml
  qml/DialogRadioButton.qml
  qml/DialogProgressBar.qml
  qml/DialogTextField.qml
    qml/DialogMultiLineEdit.qml
  qml/DialogComboBox.qml
  qml/DialogResizeHandle.qml
  qml/SemanticWidgetDelegate.qml
  qml/SemanticListPointer.qml
    qml/SemanticChoiceGroup.qml
  qml/SemanticDialogLayout.qml
  qml/SemanticGroupViewport.qml
  qml/GenericDialog.qml
  qml/SettingsDialogBody.qml
  qml/DialogOverlay.qml
  qml/AutocompletePopup.qml
  qml/SemanticMenuItemDelegate.qml
  qml/SemanticMenuPopup.qml
  qml/OverlayHost.qml
  qml/KeyBarView.qml
  qml/ToastView.qml
)
