if(NOT DEFINED RSP_FILE OR NOT EXISTS "${RSP_FILE}")
  message(FATAL_ERROR "MSVC linker response file does not exist: ${RSP_FILE}")
endif()

file(READ "${RSP_FILE}" response_content)

# CMake separates response-file arguments with two or more spaces, while a
# quoted path may legally contain the same sequence. Split only outside quoted
# arguments so builds remain valid in unusual workspace/package paths.
string(LENGTH "${response_content}" response_length)
set(normalized_content "")
set(in_quotes FALSE)
set(pending_spaces 0)
set(line_length 0)
set(max_line_length 0)

if(response_length GREATER 0)
  math(EXPR response_last "${response_length} - 1")
  foreach(index RANGE 0 ${response_last})
    string(SUBSTRING "${response_content}" ${index} 1 character)

    if(character STREQUAL "\"")
      if(pending_spaces GREATER 0)
        string(APPEND normalized_content " ")
        math(EXPR line_length "${line_length} + 1")
        set(pending_spaces 0)
      endif()
      if(in_quotes)
        set(in_quotes FALSE)
      else()
        set(in_quotes TRUE)
      endif()
    elseif(character STREQUAL " " AND NOT in_quotes)
      math(EXPR pending_spaces "${pending_spaces} + 1")
      continue()
    elseif(pending_spaces GREATER 0)
      if(pending_spaces GREATER 1)
        string(APPEND normalized_content "\n")
        if(line_length GREATER max_line_length)
          set(max_line_length ${line_length})
        endif()
        set(line_length 0)
      else()
        string(APPEND normalized_content " ")
        math(EXPR line_length "${line_length} + 1")
      endif()
      set(pending_spaces 0)
    endif()

    string(APPEND normalized_content "${character}")
    if(character STREQUAL "\n" OR character STREQUAL "\r")
      if(line_length GREATER max_line_length)
        set(max_line_length ${line_length})
      endif()
      set(line_length 0)
    else()
      math(EXPR line_length "${line_length} + 1")
    endif()
  endforeach()
endif()

if(pending_spaces GREATER 0)
  string(APPEND normalized_content " ")
  math(EXPR line_length "${line_length} + 1")
endif()
if(line_length GREATER max_line_length)
  set(max_line_length ${line_length})
endif()
if(max_line_length GREATER 16000)
  message(FATAL_ERROR
    "MSVC linker response normalization left a ${max_line_length}-byte line")
endif()

file(WRITE "${RSP_FILE}" "${normalized_content}")
