//go:build f4_embedded_qt_host

package main

import _ "embed"

// embeddedQtHostGzip is generated by the portable release build. Keeping the
// payload out of Git makes the source tree small while the build tag prevents
// ordinary developer builds from requiring a generated file.
//
//go:embed embedded/f4-qt-host.gz
var embeddedQtHostGzip []byte
