[style]
Name = Far2l Dark

[farcolors]
# Panel
Panel.Box = foreground:#555753 | background:#2E3436
Panel.Cursor = foreground:#2E3436 | background:#06989A
Panel.Cursor.Selected = foreground:#FCE94F | background:#06989A
Panel.Cursor.Inactive = foreground:#D3D7CF | background:#555753
Panel.Cursor.Inactive.Selected = foreground:#FCE94F | background:#555753
Panel.Dir = foreground:#EEEEEC | background:#2E3436
Panel.FastFindNoMatch = foreground:#CC6666 | background:#2E3436
Panel.Scrollbar = foreground:#34E2E2 | background:#2E3436
Panel.Scrollbar.Minimal = foreground:#EEEEEC | background:#2E3436
Panel.Text = foreground:#34E2E2 | background:#2E3436
Panel.Text.Highlight = foreground:#D3D7CF | background:#3465A4
Panel.Text.Info = foreground:#06989A | background:#2E3436
Panel.Text.Selected = foreground:#FCE94F | background:#2E3436
Panel.Title = foreground:#D3D7CF | background:#2E3436
Panel.Title.Column = foreground:#8AE234 | background:#2E3436
Panel.Title.Selected = foreground:#2E3436 | background:#06989A
Table.Box = foreground:#555753 | background:#2E3436
Scrollbar = foreground:#34E2E2 | background:#2E3436

# Dialog
Dialog.Box = foreground:#555753 | background:#D3D7CF
Dialog.Box.Title = foreground:#555753 | background:#D3D7CF
Dialog.Box.Title.Highlight = foreground:#555753 | background:#D3D7CF
Dialog.Text = foreground:#2E3436 | background:#D3D7CF
Dialog.Highlight = foreground:#FCE94F | background:#D3D7CF
Dialog.Edit = foreground:#EEEEEC | background:#555753
Dialog.Edit.Selected = foreground:#FCE94F | background:#4E9A06
Dialog.Edit.Unchanged = foreground:#FCE94F | background:#4E9A06
Dialog.Button = foreground:#2E3436 | background:#D3D7CF
Dialog.Button.Selected = foreground:#2E3436 | background:#4E9A06
Dialog.Button.Highlight = foreground:#FCE94F | background:#D3D7CF
Dialog.Button.Highlight.Selected = foreground:#EEEEEC | background:#4E9A06

# Warning message
WarnDialog.Box = foreground:#D3D7CF | background:#CC0000
WarnDialog.Box.Title = foreground:#EEEEEC | background:#CC0000
WarnDialog.Box.Title.Highlight = foreground:#FCE94F | background:#CC0000
WarnDialog.Text = foreground:#EEEEEC | background:#CC0000
WarnDialog.Highlight = foreground:#FCE94F | background:#CC0000
WarnDialog.Edit = foreground:#2E3436 | background:#06989A
WarnDialog.Edit.Selected = foreground:#EEEEEC | background:#555753
WarnDialog.Edit.Unchanged = foreground:#D3D7CF | background:#06989A
WarnDialog.Button = foreground:#EEEEEC | background:#CC0000
WarnDialog.Button.Selected = foreground:#2E3436 | background:#D3D7CF
WarnDialog.Button.Highlight = foreground:#FCE94F | background:#CC0000
WarnDialog.Button.Highlight.Selected = foreground:#FCE94F | background:#D3D7CF

# Menu
Menu.Box = foreground:#555753 | background:#D3D7CF
Menu.Title = foreground:#2E3436 | background:#D3D7CF
Menu.Text = foreground:#2E3436 | background:#D3D7CF
Menu.Text.Selected = foreground:#2E3436 | background:#4E9A06
Menu.Highlight = foreground:#CC0000 | background:#D3D7CF
Menu.Highlight.Selected = foreground:#CC0000 | background:#4E9A06

# Horizontal menu
MenuBar.Text = foreground:#2E3436 | background:#D3D7CF
MenuBar.Text.Selected = foreground:#2E3436 | background:#4E9A06
MenuBar.Highlight = foreground:#CC0000 | background:#D3D7CF
MenuBar.Highlight.Selected = foreground:#CC0000 | background:#4E9A06

# Key bar
KeyBar.Numbers = foreground:#D3D7CF | background:#2E3436
KeyBar.Labels = foreground:#2E3436 | background:#06989A

# Command line
CommandLine.Prompt = foreground:#D3D7CF | background:#2E3436
CommandLine.Prompt.Inactive = foreground:#555753 | background:#2E3436
CommandLine.Text = foreground:#D3D7CF | background:#2E3436
CommandLine.Text.Selected = foreground:#2E3436 | background:#D3D7CF
CommandLine.UserScreen = foreground:#D3D7CF | background:#2E3436

# Viewer
Viewer.Text = foreground:#EEEEEC | background:#555753
Viewer.Status = foreground:#2E3436 | background:#06989A
Viewer.Arrows = foreground:#FCE94F | background:#3465A4
Viewer.Scrollbar = foreground:#34E2E2 | background:#3465A4

# Editor
Editor.Text = foreground:#34E2E2 | background:#3465A4
Editor.Scrollbar = foreground:#34E2E2 | background:#3465A4
Editor.Status = foreground:#2E3436 | background:#06989A

# Help
Help.Text = foreground:#2E3436 | background:#06989A
Help.Bold = foreground:#FCE94F | background:#06989A
Help.Link = foreground:#FCE94F | background:#06989A
Help.SelectedLink = foreground:#EEEEEC | background:#555753
Help.Box = foreground:#2E3436 | background:#06989A
Help.Box.Title = foreground:#2E3436 | background:#06989A
